### PR TITLE
[CI] Update MXNet master version tested on CI

### PR DESCRIPTION
**Pull request by leezu**

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1113/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1113/1/index.html

**Comment by leezu** [comment]
Failing due to

[2020-01-15T19:27:03.256Z] OSError: /var/lib/jenkins/workspace/gluon-nlp-gpu-py3-master/conda/gpu/py3-master/lib/python3.5/site-packages/horovod/mxnet/mpi_lib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _Z20MXAPIHandleExceptionRKSt9exception


https://github.com/apache/incubator-mxnet/issues/17292

**Comment by leezu** [comment]
@xinyu-intel I'm disabling the horovod test on master. That will allow you to test https://github.com/dmlc/gluon-nlp/pull/1080 better (though your PR can't be merged prior to 0.9 release)

**Comment by mli** [comment]
Job PR-1113/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1113/3/index.html

**Comment by mli** [comment]
Job PR-1113/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1113/4/index.html

**Pull request merged**
