### PR TITLE
Used fixed seed for test_beam_search

### LINKED ISSUE #72: Beam search tests are flaky
Once in a while the tests introduced in #20 will fail:

 ```
       # Begin Testing

        for vocab_num in [4, 8]:

            for decoder_fn in [RNNDecoder,

                               functools.partial(RNNDecoder2, use_tuple=False),

                               functools.partial(RNNDecoder2, use_tuple=True)]:

                decoder = decoder_fn(vocab_num=vocab_num, hidden_size=HIDDEN_SIZE)

                decoder.hybridize()

                decoder.initialize()

                for beam_size, bos_id, eos_id, alpha, K in [(2, 1, 3, 0, 1.0),  (4, 2, 3, 1.0, 5.0)]:

                    scorer = BeamSearchScorer(alpha=alpha, K=K)

                    for max_length in [10, 20]:

                        sampler = BeamSearchSampler(beam_size=beam_size, decoder=decoder, eos_id=eos_id,

                                                    scorer=scorer, max_length=max_length)

                        for batch_size in [1, 2, 5]:

                            states = decoder.begin_state(batch_size)

                            inputs = mx.nd.full(shape=(batch_size,), val=bos_id)

                            samples, scores, valid_length = sampler(inputs, states)

                            samples = samples.asnumpy()

                            scores = scores.asnumpy()

                            valid_length = valid_length.asnumpy()

                            for i in range(batch_size):

                                max_beam_valid_length = int(np.round(valid_length[i].max()))

                                step_states = _fetch_step_states(states, i, beam_size)

                                step_input = bos_id

                                npy_samples = _npy_beam_search(decoder, scorer, step_input, step_states,

                                                               eos_id, beam_size, max_length)

>                               assert_allclose(npy_samples, samples[i, :, :max_beam_valid_length])

E                               AssertionError: 

E                               Not equal to tolerance rtol=1e-07, atol=0

E                               

E                               (mismatch 20.8333333333%)

E                                x: array([[1., 2., 0., 2., 0., 2., 0., 2., 2., 0., 2., 3.],

E                                      [1., 2., 0., 2., 0., 2., 0., 2., 2., 2., 2., 3.]])

E                                y: array([[1, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 3],

E                                      [1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 3]], dtype=int32)


tests/unittest/test_beam_search.py:184: AssertionError

```

Should we fix the seed for these tests? If so we can simply add the `@pytest.mark.seed(1)` decorator.

### PR DESCRIPTION
**Pull request by leezu**
Fixes #72

### CODE REVIEW

**Comment by mli** [comment]
Job PR-99/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-99/2/index.html

**Comment by szha** [comment]
@leezu @sxjscience what's the root cause for the test failure? is it a code problem?

**Comment by leezu** [comment]
I suggest we merge this now as it is annoying to retrigger CI if it failed due to test_beam_search. Regarding the root cause, @sxjscience is in a better position to answer as he wrote that code. Even if this is a code problem, it's in the code already and if so @sxjscience is aware and can fix it or let us know to fix it if he is busy?

**Comment by sxjscience** [comment]
We can merge this in first. I’m busy this week.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
