### PR TITLE
Adopt src/gluonnlp folder layout

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Currently our tests do not run against the package as it will be installed by
its users. They run against whatever the situation in the project directory is.
This is bad. See: https://hynek.me/articles/testing-packaging/

### Essentials ###
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Change project layout: move gluonnlp folder to src/gluonnlp 

## Comments ##
- For example http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-389/6/ failed as the compiled cython files are at the install location, however the tests run on the project source folder. Consequently, as the compiled library files are not present in the source folder, the tests fail.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-390/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/3/index.html

**Comment by mli** [comment]
Job PR-390/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/4/index.html

**Comment by mli** [comment]
Job PR-390/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/5/index.html

**Comment by szha** [comment]
I still see warnings like `tests/unittest/corpora/test_wikitext.py::test_wikitext2_raw Coverage.py warning: Module gluonnlp has no Python source. (module-not-python)`

**Comment by mli** [comment]
Job PR-390/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/8/index.html

**Comment by mli** [comment]
Job PR-390/9 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/9/index.html

**Comment by mli** [comment]
Job PR-390/11 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/11/index.html

**Comment by mli** [comment]
Job PR-390/15 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-390/15/index.html

**Pull request merged**
