### PR TITLE
Ci time

### PR DESCRIPTION
**Pull request by szha**
## Description ##
reduce test time

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] don't clean hosted datasets
- [x] reduce epochs to 1 in script tests
- [x] make deploy step parallel

### CODE REVIEW

**Comment by szha** [comment]
#302 #308

**Comment by mli** [comment]
Job PR-315/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-315/1/index.html

**Comment by mli** [comment]
Job PR-315/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-315/2/index.html

**Comment by mli** [comment]
Job PR-315/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-315/6/index.html

**Comment by mli** [comment]
Job PR-315/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-315/8/index.html

**Pull request merged**
