### PR TITLE
Change SimVerb3500 URL to aclweb hosted version

### PR DESCRIPTION
**Pull request by leezu**
cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by sxjscience** [comment]
Good for merge if the CI passes this time. 👍

**Comment by mli** [comment]
Job PR-979/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-979/1/index.html

**Comment by mli** [comment]
Job PR-979/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-979/2/index.html

**Comment by mli** [comment]
Job PR-979/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-979/3/index.html

**Pull request merged**
