### PR TITLE
fix ppl reporting for training on multi gpu

### PR DESCRIPTION
**Pull request by ThomasDelteil**
The loss is added n times per iteration where n is number of GPUs, it should be divided by the length of the context

## Description ##
Fix example

### CODE REVIEW

**Comment by szha** [comment]
@ThomasDelteil thanks for the fix. @cgraywang may want to take a look.

**Comment by mli** [comment]
Job PR-365/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-365/1/index.html

**Comment by cgraywang** [comment]
Thanks for the fix @ThomasDelteil .

**Comment by ThomasDelteil** [comment]
@cgraywang makes sense, updated

**Comment by mli** [comment]
Job PR-365/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-365/4/index.html

**Comment by ThomasDelteil** [comment]
@cgraywang ping

**Comment by cgraywang** [comment]
@ThomasDelteil thanks for the contribution.

**Pull request merged**
