### PR TITLE
Fix badge icon

### PR DESCRIPTION
**Pull request by hetong007**
## Description ##
Fix broken badge icon in readme file.

### Essentials ###
- [X] Changes are complete (i.e. I finished coding on this PR)

Reference: https://github.com/dmlc/gluon-cv/pull/837

### CODE REVIEW

**Comment by mli** [comment]
Job PR-800/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-800/1/index.html

**Comment by mli** [comment]
Job PR-800/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-800/2/index.html

**Comment by leezu** [comment]
Do you know why http://ci.mxnet.io/buildStatus/icon?job=gluon-nlp%2Fmaster says "build not run"?

**Comment by hetong007** [comment]
@szha do you have better understanding in it? 
In principal this badge shows the status for master branch building status, and for gluoncv it works well. Could you make sure that the master branch has been built?

**Comment by szha** [comment]
@leezu @hetong007 after breaking the single pipeline into multiple pipelines, the job that the icon linked to is no longer used.

**Comment by mli** [comment]
Job PR-800/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-800/3/index.html

**Comment by hetong007** [comment]
@szha would you please restart the flaky tests?

**Pull request merged**
