### PR TITLE
[CI] Add Volume to g4dn.4x 

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
To solve issue #1361 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Review by sxjscience — APPROVED** [review]

**Review by leezu — COMMENTED** [review]
Thank you @barry-jin! I wonder why not update the existing job type instead of creating a new one?

**Comment by sxjscience** [comment]
For me, I think we can also directly update the g4dn.4x (In fact, we may try to increase the disk space of all the G4 instances).

**Comment by barry-jin** [comment]
Ok, let me directly update g4dn.4x.

**Comment by barry-jin** [comment]
Updated g4dn job queue and re-run [this job](https://github.com/dmlc/gluon-nlp/actions/runs/276908007).

**Pull request closed without merging**
