### PR TITLE
[TUTORIAL] Use FixedBucketSampler in BERT tutorial for better performance

### PR DESCRIPTION
**Pull request by Ishitori**
## Description ##
Follow up on BERT tutorial https://github.com/dmlc/gluon-nlp/issues/425 - use FixedBucketSampler for better wall clock performance.

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)

### CODE REVIEW

**Comment by mli** [comment]
Job PR-506/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-506/1/index.html

**Comment by eric-haibin-lin** [comment]
Do you mind also replacing 
```
        grads = [p.grad(c) for p in params for c in [ctx]]
        gluon.utils.clip_global_norm(grads, grad_clip)
```
with 
```
      nlp.utils.clip_grad_global_norm(params, grad_clip)
```
Like what was did in https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/finetune_classifier.py#L215

**Comment by astonzhang** [comment]
@Ishitori would you like to address the comment by @eric-haibin-lin ? It will take about 1 minute. Thanks.

**Comment by mli** [comment]
Job PR-506/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-506/2/index.html

**Pull request merged**
