### PR TITLE
[BUGFIX] Update BERT test and pre-train script

### LINKED ISSUE #660: Find a Bug in pretrain script of bert
https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/run_pretraining.py

line 296 and 297,throw a exception：

```
Traceback (most recent call last):
  File "/home/xzc/gluon-nlp/scripts/bert/run_pretraining.py", line 477, in <module>
    evaluate(data_eval, model, nsp_loss, mlm_loss, len(vocabulary), ctx)
  File "/home/xzc/gluon-nlp/scripts/bert/run_pretraining.py", line 297, in evaluate
    mlm_metric.reset_running()
AttributeError: 'MaskedAccuracy' object has no attribute 'reset_running'
```

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
fix #660 
Also fixes the test case for BERT so that this can be properly caught. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@Deseaus please help review. Thanks!

**Comment by Deseaus** [comment]
I probably introduced this while renaming the variables, thanks for fixing!

**Comment by mli** [comment]
Job PR-661/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-661/2/index.html

**Comment by mli** [comment]
Job PR-661/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-661/5/index.html

**Pull request merged**
