### PR TITLE
[DATASET] add LCQMC, ChnSentiCorp dataset

### PR DESCRIPTION
**Pull request by paperplanet**
## Description ##
add LCQMC, ChnSentiCorp dataset

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mli** [comment]
Job PR-774/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-774/1/index.html

**Comment by paperplanet** [comment]
> Thanks! What are the licenses of these datasets? Could you add them to the classes?
> If the dataset licenses are friendly, we can consider redistributing them.

OK, I can add the license for LCQMC and XNLI.
LCQMC is licensed under a Creative Commons Attribution 4.0 International License. License details: http://creativecommons.org/licenses/by/4.0/. XNLI has Attribution-NonCommercial 4.0 International 
 license : https://github.com/facebookresearch/XNLI/blob/master/LICENSE, (https://creativecommons.org/licenses/by-nc/4.0/). But I can't find ChnSentiCorp's license. All these dataset are redistributed by baidu. Seems we can at least redistribute XNLI and LCQMC.

**Comment by szha** [comment]
We probably can't redistribute XNLI due to the non-commercial license.

**Comment by mli** [comment]
Job PR-774/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-774/2/index.html

**Comment by mli** [comment]
Job PR-774/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-774/3/index.html

**Comment by paperplanet** [comment]
> We probably can't redistribute XNLI due to the non-commercial license.

Oh. What a pity.

**Comment by eric-haibin-lin** [comment]
> We probably can't redistribute XNLI due to the non-commercial license.

It only means that we cannot host the dataset, right? Using external links is fine?

**Comment by szha** [comment]
> It only means that we cannot host the dataset, right? Using external links is fine?

yes that's what I meant

**Comment by mli** [comment]
Job PR-774/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-774/4/index.html

**Comment by mli** [comment]
Job PR-774/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-774/5/index.html

**Comment by mli** [comment]
Job PR-774/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-774/6/index.html

**Pull request merged**
