### PR TITLE
[DOC] Cite source of pretrained parameters for bert_12_768_12

### LINKED ISSUE #896: Citation for converted BERT model
We shall explicitly cite the converted BERT models on the website to avoid confusions. For example, there are multiple ClinicalBERT model repositories and papers: 
https://github.com/EmilyAlsentzer/clinicalBERT
https://github.com/kexinhuang12345/clinicalBERT
@leezu

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Cite source of pretrained parameters for bert_12_768_12 in docstring and on modelzoo.

Fixes #896

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- Cite source of pretrained parameters for bert_12_768_12

## Comments ##
- @eric-haibin-lin

### CODE REVIEW

**Comment by mli** [comment]
Job PR-915/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-915/1/index.html

**Comment by leezu** [comment]
Don't merge yet, turns out there is some issue with the links on the http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-915/1/model_zoo/bert/index.html

**Comment by leezu** [comment]
Should be good now

**Comment by mli** [comment]
Job PR-915/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-915/2/index.html

**Pull request merged**
