### PR TITLE
[API] Try to use the new None feature in MXNet + Drop support for MXNet 1.5

### PR DESCRIPTION
**Pull request by sxjscience**
## Description ##

Since we have supported None in HybridBlock of Gluon (https://github.com/apache/incubator-mxnet/pull/16280), remove all the hacks. 

The change will force GluonNLP to rely on the nightly-build of MXNet.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

## Comments ##
- It should be considered as a backward incompatible change because the user must upgrade to the latest MXNet

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-967/19 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-967/19/index.html

**Comment by mli** [comment]
Job PR-967/20 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-967/20/index.html

**Comment by sxjscience** [comment]
Find that the SimVerb is still not available, should we exclude it or upload it into S3?

**Comment by mli** [comment]
Job PR-967/21 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-967/21/index.html

**Comment by sxjscience** [comment]
> Are we going to replace mxnet nightly version with a custom pip wheel on s3?

We need to create one... I do not know how to do that though

**Pull request merged**
