### PR TITLE
[DOC] Fix sphinx-autorun errors on website

### LINKED ISSUE #788: simverb3500 link broken
## Description
http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-783/3/pipeline#step-64-log-1246

## What have you tried to solve it?

We will skip its test for now which needs to be added back.

### LINKED ISSUE #809: Sphinx-autorun output broken on website
## Description
The autorun output on our master-branch version of the website is broken. All current PRs are also affected. The last stable release was still working.

Stable: http://gluon-nlp.mxnet.io/api/modules/embedding.html#gluonnlp.embedding.GloVe
Master: http://gluon-nlp.mxnet.io/master/api/modules/embedding.html#gluonnlp.embedding.GloVe

```

  File "<input>", line 1
    -
    ^
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by leezu**
### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

## Comments ##
Fixes #809 
Fixes #788

### CODE REVIEW

**Comment by mli** [comment]
Job PR-807/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-807/1/index.html

**Comment by leezu** [comment]
Not sure why there is now

```
  File "<input>", line 1
    -
    ^
SyntaxError: invalid syntax
```

http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-807/1/api/modules/embedding.html#gluonnlp.embedding.GloVe

**Comment by mli** [comment]
Job PR-807/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-807/2/index.html

**Comment by szha** [comment]
not sure. maybe runblock doesn't support the ellipsis tag `-etc-`?

**Comment by leezu** [comment]
Looking at the website builds of the Master branch ( http://gluon-nlp.mxnet.io/master/api/modules/embedding.html#gluonnlp.embedding.GloVe ), the error shows up there as well.
A regression must have been introduced since the last release, since the stable website is fine: http://gluon-nlp.mxnet.io/api/modules/embedding.html#gluonnlp.embedding.GloVe


Tracking in #809

**Comment by mli** [comment]
Job PR-807/7 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-807/7/index.html

**Comment by mli** [comment]
Job PR-807/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-807/8/index.html

**Comment by leezu** [comment]
Please take a look and potentially merge @eric-haibin-lin @szha

**Comment by mli** [comment]
Job PR-807/9 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-807/9/index.html

**Pull request merged**
