### PR TITLE
Remove gluon.utils.download copy with verify_ssl support

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
The problematic server now servers a valid SSL certificate. Also https://github.com/apache/incubator-mxnet/pull/11546 will add the option upstream.

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### CODE REVIEW

**Comment by szha** [comment]
We will need to wait until we update the dependency with a nightly version that includes the update in download before we merge.

**Comment by leezu** [comment]
Currently the updated `download` is not needed any more, because the third-party server was fixed. I proposed the change in mxnet as we may run into similar issues in future.

**Comment by leezu** [comment]
It turns out the webserver is still not fixed. The issue is that it does not serve an intermediary certificate that is needed to establish the trust from the root CA to the websites certificate. Newer browsers include the intermediary certificate used, so no error is shown when accessing the file with Firefox.

I have contacted the admin and asked to include the intermediary certificates.  More info about the certificate issues can be found here https://www.ssllabs.com/ssltest/analyze.html?d=ie.technion.ac.il

**Comment by mli** [comment]
Job PR-193/16 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-193/16/index.html

**Comment by szha** [comment]
@leezu it passed. Was the issue upstream fixed?

**Comment by leezu** [comment]
No, I made use of the verify_ssl=False that was added to upstream mxnet.

**Comment by leezu** [comment]
I haven't received a response from the webmaster. They seem unwilling to fix their server.

**Pull request merged**
