### PR TITLE
adaptive softmax

### PR DESCRIPTION
**Pull request by dofuer99**
## Description ##
2018 Geekthon Camp, Beijing. 
Implementation of 'Efficient softmax approximation for GPUs' via MXNet.
Experiments on data set 'Text8' have been conducted and the results are similar to that reported 
from the publication.

The code is written by Duo Zeng, who is a student from Technical University of Munich.
This task is supervised by Haibin Lin, who works in AWS NLP group.

## Checklist ##
The complete test case is added in '/gluon-nlp/scripts/adaptive_softmax'

### CODE REVIEW

**Comment by szha** [comment]
@dofuer99 @eric-haibin-lin I created "adasoft" branch for you two to work on. Good luck!

**Comment by eric-haibin-lin** [comment]
@dofuer99 see difference of API changes, scripts and examples here: https://github.com/dmlc/gluon-nlp/blob/master/docs/how_to/contribute.rst#contribute-scripts 
Also there's text8 dataset API available now

**Comment by szha** [comment]
Done. Please do a rebase.

**Comment by mli** [comment]
Job PR-255/34 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-255/34/index.html

**Pull request merged**
