### PR TITLE
Update GBW vocab

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
 #291

### Essentials ###
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Update vocab after #282

## Comments ##
- Change is still being verified

### CODE REVIEW

**Comment by mli** [comment]
Job PR-292/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-292/1/index.html

**Comment by mli** [comment]
Job PR-292/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-292/2/index.html

**Comment by mli** [comment]
Job PR-292/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-292/3/index.html

**Comment by eric-haibin-lin** [comment]
I made the update in #294

**Pull request closed without merging**
