### PR TITLE
[BUGFIX] use glove.840B.300d for NLI experiments

### PR DESCRIPTION
**Pull request by hhexiy**
## Description ##
Use glove.840B.300d instead of glove.6B.300d. Updated accuracy numbers.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] default embedding is glove.840B.300d

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mli** [comment]
Job PR-567/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-567/1/index.html

**Comment by szha** [comment]
@hhexiy https://github.com/dmlc/web-data/pull/153 has been merged.

**Comment by mli** [comment]
Job PR-567/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-567/1/index.html

**Comment by mli** [comment]
Job PR-567/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-567/2/index.html

**Comment by mli** [comment]
Job PR-567/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-567/4/index.html

**Pull request merged**
