### PR TITLE
[BUGFIX] Fix bugs in BERT export script

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
For some reason the `test_export` test in integration test was not run (?) for previous PRs? @leezu 

Fixing the bug here. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by leezu** [comment]
Probably our `-k SELECTOR` expressions for the different jobs don't cover all possibilities, ie. ```
@pytest.mark.serial
@pytest.mark.integration
``` is ignored by all Jenkins jobs.

**Comment by leezu** [comment]
In particular tests that are not marked with gpu but are marked with integration..

**Comment by mli** [comment]
Job PR-944/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-944/1/index.html

**Comment by mli** [comment]
Job PR-944/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-944/2/index.html

**Comment by mli** [comment]
Job PR-944/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-944/4/index.html

**Comment by eric-haibin-lin** [comment]
v0.8 still have `BERTClassifier, BERTRegression` in  `model.classification`, the script was not broken. (The `BERTClassifier` API  is added to nlp.model this week). The only incorrect thing is that in 0.8, the test uses a wrong path to `export.py`. But that test is not enabled in 0.8 either. 

For users at v0.8, the documentation for export is correct, so it won't affect them.

**Pull request merged**
