### PR TITLE
[DOC] Improve BERT fine-tuning tutorial

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
Add more explanation for a few places in the BERT fine-tuning tutorial, specially on the data format and data preprocessing. Preview: http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-622/2/examples/sentence_embedding/bert.html 
@berenluthien could you also help review?

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mli** [comment]
Job PR-622/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-622/2/index.html

**Comment by mli** [comment]
Job PR-622/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-622/1/index.html

**Comment by eric-haibin-lin** [comment]
@pengxin99 nice catch. I'll fix it

**Comment by eric-haibin-lin** [comment]
https://github.com/dmlc/gluon-nlp/pull/628

**Pull request merged**
