### PR TITLE
Scripts for producing the figures that explain the bucketing strategy

### PR DESCRIPTION
**Pull request by sxjscience**
Here's the script I used to plot the figures that explain different bucketing strategies (The figures in http://gluon-nlp.mxnet.io/api/notes/data_api.html). I choose to upload it here in case the others would like to use it in the future.

### CODE REVIEW

**Comment by sxjscience** [comment]
For the color combinations, I manually selected from https://coolors.co/ .

**Comment by mli** [comment]
Job PR-908/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-908/1/index.html

**Comment by mli** [comment]
Job PR-908/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-908/4/index.html

**Comment by eric-haibin-lin** [comment]
Nice. If we can take a BucketSampler as the input and output the visualization, it will be even easier for other to use.

**Pull request merged**
