### PR TITLE
[BUGFIX] Fix bug in issue #1570

### PR DESCRIPTION
**Pull request by DOUDOU0314**
## Description ##
(Brief description on what this PR is about)
fix bug in issue #1570: XLMR Conversion fails on parameter dictionary KeyError

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- I modified parameters name in latest version of fairseq

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by leezu** [comment]
CI failed with
```

[2021-05-20T06:26:19.155Z] Configuration error:
[2021-05-20T06:26:19.155Z] Unknown key(s) in sphinx_gallery_conf:
[2021-05-20T06:26:19.155Z] 'find_mayavi_figures'
```

FYI @barry-jin

**Review by sxjscience — COMMENTED** [review]
Would you also attach the version of fairseq? The root cause is that fairseq has been upgraded.

**Comment by sxjscience** [comment]
@DOUDOU0314 Would you merge the master and also attach the current version of fairseq?

**Comment by DOUDOU0314** [comment]
> @DOUDOU0314 Would you merge the master and also attach the current version of fairseq?
I've attached a stable version of fairseq, in which the former parameters name can be retained. And fix a bug under this version.

**Review by sxjscience — APPROVED** [review]

**Pull request merged**
