### PR TITLE
[BUGFIX] [DOC] Update nlp.model.get_model documentation and get_model API

### PR DESCRIPTION
**Pull request by leezu**
http://gluon-nlp.mxnet.io/api/modules/model.html currently does not
differentiate pre-defined models exposed by the `get_model` function and other
components. This PR is a quick attempt to improve the distinction.

Further, `get_model` used a hardcoded `dataset=wikitext-2` argument. This is
likely by accident as the `get_model` function was initially mainly used for
language models, but now also provides access to other models such as Bert, for
which hardcoded dataset argument does not make sense.

For example, loading a Bert model with a prespecified Vocab currently requires doing

    nlp.model.get_model('bert_12_768_12', dataset_name=None, vocab=vocabulary, ...)

instead of

    nlp.model.get_model('bert_12_768_12', vocab=vocabulary, ...)
    
The latter version currently fails, as it will pass the "wikitext-2" as
dataset_name to the Bert model constructor.

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Change `nlp.model.get_model` dataset argument default to None
- [X] Improve `nlp.model` docs

### CODE REVIEW

**Comment by mli** [comment]
Job PR-734/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-734/2/index.html

**Comment by eric-haibin-lin** [comment]
The `Segmentation fault: 11` in CI seems unrelated, but I didn't notice similar failures recently ..

**Comment by mli** [comment]
Job PR-734/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-734/3/index.html

**Comment by leezu** [comment]
I'm restarting the failed pipeline http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py2-gpu-unittest/detail/PR-734/3/pipeline as http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py2-gpu-unittest/detail/PR-734/4/pipeline

**Pull request merged**
