### PR TITLE
remove convert_all.sh

### PR DESCRIPTION
**Pull request by ZheyuYe**
## Description ##
Will fix https://github.com/dmlc/gluon-nlp/issues/1347

cc @sxjscience

### CODE REVIEW

**Review by sxjscience — APPROVED** [review]

**Comment by szha** [comment]
@sxjscience do we really need this script? I'm not sure if this is useful to users and this file seems like a place where new addition would be missed.

**Comment by sxjscience** [comment]
It's also fine to directly move this file.

**Comment by sxjscience** [comment]
@ZheyuYe Would you remove this file?

**Comment by sxjscience** [comment]
@szha Would you have other concerns?

**Pull request merged**
