### PR TITLE
[Enhancement] Mix precision support for BERT finetuning

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
- clean up and update documentation
- add dtype option to the finetuning script, using AMP

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@ptrendx FYI

**Comment by mli** [comment]
Job PR-793/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-793/1/index.html

**Comment by mli** [comment]
Job PR-793/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-793/2/index.html

**Comment by mli** [comment]
Job PR-793/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-793/3/index.html

**Comment by mli** [comment]
Job PR-793/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-793/4/index.html

**Comment by mli** [comment]
Job PR-793/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-793/5/index.html

**Comment by eric-haibin-lin** [comment]
@ptrendx i think there're multiple places where the range of the scalar (eps, or negative value like this)  to an op may be too large or too small for fp16. Is there a better way to fix/truncate them in AMP instead of user's code?

**Pull request merged**
