### PR TITLE
[DOC] update installation guide with selectors

### PR DESCRIPTION
**Pull request by szha**
## Description ##
update installation guide by adopting the selectors from CV

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] update installation guide with selectors

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-966/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-966/6/index.html

**Comment by leezu** [comment]
Thanks @szha 

Screenshot from 2019-10-11 17-44-47

How about left-aligning the buttons?

The claim that Python 2 is supported is wrong.

**Comment by mli** [comment]
Job PR-966/7 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-966/7/index.html

**Comment by mli** [comment]
Job PR-966/9 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-966/9/index.html

**Comment by mli** [comment]
Job PR-966/10 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-966/10/index.html

**Pull request merged**
