### PR TITLE
[CI] AWS Batch serverless CI Pipeline for parallel notebook execution during website build step

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Currently our CI takes more than 1 hour, running multiple Jenkinsfiles in parallel. The longest running is GluonNLP-py3-master-gpu-doc with expected runtime to gradually worsen as we add more examples.

This PR speeds up the GluonNLP-py3-master-gpu-doc run by parallelizing execution of our example notebooks with AWS Batch, scheduling a separate Job for each notebook. As a result, GluonNLP-py3-master-gpu-doc only runs 30 minutes, out of which 10 minutes are spent waiting for AWS Batch to begin execution. As AWS Batch service is expected to improve, we may hope for an execution time of ~20 minutes in the future.

Now, GluonNLP-py3-master-gpu-integration and GluonNLP-py3-gpu-integration are our longest running Jenkinsfiles.

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] Serverless CI Pipeline based on AWS Batch

### CODE REVIEW

**Comment by leezu** [comment]
@szha, please help to update the IAM Instance Profile:
`
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the SubmitJob operation: User: arn:aws:iam::650140442593:user/s3-write is not authorized to perform: batch:SubmitJob on resource: arn:aws:batch:us-east-1:650140442593:job-definition/gluon-nlp-jobs:6
`
http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-791/35/pipeline/

**Comment by mli** [comment]
Job PR-791/113 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-791/113/index.html

**Comment by mli** [comment]
Job PR-791/123 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-791/123/index.html

**Comment by leezu** [comment]
@szha @eric-haibin-lin please review and merge if everything looks good to you

**Pull request merged**
