### PR TITLE
[BUGFIX] update paths and imports in bert scripts

### PR DESCRIPTION
**Pull request by szha**
## Description ##
update paths and imports in bert scripts

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] update paths and imports in bert scripts

### CODE REVIEW

**Comment by mli** [comment]
Job PR-634/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-634/2/index.html

**Comment by mli** [comment]
Job PR-634/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-634/3/index.html

**Comment by szha** [comment]
The compare script passes only with google/bert@f39e881b169b9d53bea03d2d341b31707a6c052b, not the current master.

**Comment by mli** [comment]
Job PR-634/7 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-634/7/index.html

**Pull request merged**
