### PR TITLE
[CI] Update MXNet master version tested on CI (#1113)

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
(Brief description on what this PR is about)

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1176/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1176/1/index.html

**Comment by eric-haibin-lin** [comment]
nightly build, i think. @szha please feel free to comment

**Comment by leezu** [comment]
```
% md5sum mxnet-1.6.0-py2.py3-none-manylinux1_x86_64.whl                                  ~/src/mxnet-master/build citestcmake ip-172-31-95-96
be9cf7c44761be982e3c47728f0e2bf3  mxnet-1.6.0-py2.py3-none-manylinux1_x86_64.whl

% md5sum mxnet-1.6.0b20200224-py2.py3-none-manylinux1_x86_64.whl                         ~/src/mxnet-master/build citestcmake ip-172-31-95-96
15834d95495f4248b18a9714e5903481  mxnet-1.6.0b20200224-py2.py3-none-manylinux1_x86_64.whl

```

The link you use doesn't seem to refer to the latest nightly build.

**Comment by eric-haibin-lin** [comment]
I'm cherry-picking the changes in https://github.com/dmlc/gluon-nlp/pull/1152/files back to v0.9. Should the master branch be updated, too?

**Pull request merged**
