### PR TITLE
[Tests] Improve test robustness

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Improve robustness of our tests so that they can also run in other environments.

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-960/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-960/1/index.html

**Comment by mli** [comment]
Job PR-960/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-960/4/index.html

**Comment by mli** [comment]
Job PR-960/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-960/6/index.html

**Comment by leezu** [comment]
Confirmed that the MXNET_HOME environment variable is correctly used on CI.
For example, `bert_12_768_12_wiki_multilingual_uncased-237f3985.params` is now placed correctly at 
`/var/lib/jenkins/workspace/gluon-nlp-cpu-py3@6/tests/data/models/bert_12_768_12_wiki_multilingual_uncased-237f3985.params` with `MXNET_HOME=tests/data/`

**Pull request merged**
