### PR TITLE
[TUTORIAL] Fix README WikiText2 example

### PR DESCRIPTION
**Pull request by crcrpar**
## Description ##
This fixes `nlp.data.WikiText2(segment='train')[0][0:5]` to `nlp.data.WikiText2(segment='train')[0:5]` because `nlp.data.WikiText2(segment='train')[0][0:5]` is '='.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@szha is the CI down?

**Comment by szha** [comment]
@eric-haibin-lin a recent kernel image upgrade on the CI server caused nvidia drivers to fail. I reverted the kernel images just now so hopefully, things should be working now

**Comment by mli** [comment]
Job PR-681/11 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-681/11/index.html

**Comment by szha** [comment]
@crcrpar thank you for the fix!

**Comment by crcrpar** [comment]
My pleasure!

**Pull request merged**
