### PR TITLE
fix cache bugs

### PR DESCRIPTION
**Pull request by szha**
## Description ##
fix cache language model script bugs

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [x] fix usage of batchify
- [x] fix cache language model script commands

### CODE REVIEW

**Comment by szha** [comment]
Reported in https://discuss.gluon.ai/t/topic/7620/17

**Comment by mli** [comment]
Job PR-324/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-324/2/index.html

**Comment by mli** [comment]
Job PR-324/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-324/3/index.html

**Comment by mli** [comment]
Job PR-324/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-324/4/index.html

**Pull request merged**
