### PR TITLE
[FIX]fix chnsenticorp dataset download link

### PR DESCRIPTION
**Pull request by paperplanet**
## Description ##
fix XNLI, LCQMC, ChnSentiCorp dataset download link

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### CODE REVIEW

**Comment by mli** [comment]
Job PR-873/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-873/3/index.html

**Comment by mli** [comment]
Job PR-873/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-873/4/index.html

**Comment by paperplanet** [comment]
Because Baidu do not host lcqmc any more. I disabled test for lcqmc dataset.

**Comment by leezu** [comment]
How can people obtain LCQMC now? Should it be documented?

**Comment by paperplanet** [comment]
Baidu recommended email the author of the dataset. But the data format of the dataset people get from author may different from the one Baidu used to host. May be we should delete the code for lcqmc dataset?

**Comment by leezu** [comment]
According to the docstring, the dataset is licensed under a Creative Commons Attribution 4.0 International License. Thus we could redistribute it. Is this license statement correct? If so, how about we redistribute the dataset instead of deleting it?

**Comment by paperplanet** [comment]
Good idea! License information is correct. It is written in their paper:  https://www.aclweb.org/anthology/C18-1166

**Comment by leezu** [comment]
The license in the footer of the paper refers only to the paper itself. Looking at http://icrc.hitsz.edu.cn/LCQMC_Application_Form.pdf (linked via the website mentioned in the paper), the dataset is not published under CC. Based on the Terms and Application Form of using LCQMC we unfortunately do not have the right to redistribute it.

Could you fix the licensing information in the docstring? Something like the following would be correct: "No license granted. You can request a private license via http://icrc.hitsz.edu.cn/LCQMC_Application_Form.pdf"

**Comment by paperplanet** [comment]
It looks strange to me.
Yeah, the docstring is fixed.

**Comment by mli** [comment]
Job PR-873/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-873/5/index.html

**Pull request merged**
