### PR TITLE
[DOC] remove py3 usage from the doc

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
remove py3 usage from the doc

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
@leezu have you seen this before? It's strange that such an error show up in this PR
```
[2019-12-22T20:58:48.064Z] No matching distribution found for entrypoints<0.4.0,>=0.3.0 (from flake8==3.7.9->-r /var/lib/jenkins/workspace/gluon-nlp-cpu-py3@4/env/cpu/condaenv.jz7nalw1.requirements.txt (line 11))


```

**Comment by leezu** [comment]
@eric-haibin-lin where did you meet this error? I can't find it in the current log.
However, there seems to be a numpy related issue. It may be due to numpy 1.18 release.

**Comment by leezu** [comment]
Let's pin the numpy version for now. Looks like seaborn library used by one of the doc scripts is incompatible with numpy 1.18

**Comment by mli** [comment]
Job PR-1077/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1077/2/index.html

**Pull request merged**
