### PR TITLE
[BUGFIX] Fix doc (was: Update sampler.py)

### PR DESCRIPTION
**Pull request by anuragsarkar97**
fixed bug

[BUG_FIX]

### CODE REVIEW

**Comment by mli** [comment]
Job PR-583/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-583/2/index.html

**Comment by szha** [comment]
@anuragsarkar97 thank you for the fix! The preview can be found here: http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-583/2/api/modules/data.html#gluonnlp.data.FixedBucketSampler

Looks like it still needs some fixing. Could you take a look? Thanks!

**Comment by anuragsarkar97** [comment]
sure looking into it. 👍

**Comment by mli** [comment]
Job PR-583/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-583/3/index.html

**Comment by mli** [comment]
Job PR-583/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-583/4/index.html

**Comment by mli** [comment]
Job PR-583/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-583/6/index.html

**Comment by mli** [comment]
Job PR-583/7 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-583/7/index.html

**Comment by szha** [comment]
@anuragsarkar97 thanks a lot for the fix!

**Pull request merged**
