### PR TITLE
Add unknown_lookup setter to TokenEmbedding

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Add unknown_lookup setter to TokenEmbedding

### Essentials ###
- [X] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Add unknown_lookup setter to TokenEmbedding
- [X] Allow initializing TokenEmbedding.idx_to_vec by extending the token embedding

## Comments ##
@Ishitori @szha

### CODE REVIEW

**Comment by leezu** [comment]
I suggest to include this for 0.5 so that @Ishitori use-case can be handled more easily.

**Comment by mli** [comment]
Job PR-429/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-429/1/index.html

**Comment by mli** [comment]
Job PR-429/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-429/3/index.html

**Comment by mli** [comment]
Job PR-429/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-429/5/index.html

**Comment by szha** [comment]
@leezu thanks for the quick fix. It would be great if you could update the tutorial to reflect this usage later.

**Pull request merged**
