### PR TITLE
[DOC] update download button in tutorial and model zoo

### PR DESCRIPTION
**Pull request by szha**
## Description ##
doc website fixes.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)

### Changes ###
- [x] update download button in tutorial and model zoo. download buttons are now after the first header in the form of a button.
- [x] allow horizontal scroll when there is content overflow. (e.g. the huge table in [language model](http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/8/model_zoo/language_model/index.html))
- [x] make navbar responsive.
- [x] make header links `¶` appear when hovering the title.

### Comments ###
- Require https://github.com/mli/mx-theme/pull/3 to be merged first.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-746/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/1/index.html

**Comment by mli** [comment]
Job PR-746/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/2/index.html

**Comment by eric-haibin-lin** [comment]
The TOC sidebar looks fine here @szha

**Comment by mli** [comment]
Job PR-746/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/3/index.html

**Comment by mli** [comment]
Job PR-746/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/4/index.html

**Comment by mli** [comment]
Job PR-746/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/5/index.html

**Comment by mli** [comment]
Job PR-746/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/6/index.html

**Comment by mli** [comment]
Job PR-746/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/8/index.html

**Comment by mli** [comment]
Job PR-746/9 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/9/index.html

**Comment by mli** [comment]
Job PR-746/10 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/10/index.html

**Comment by mli** [comment]
Job PR-746/11 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/11/index.html

**Comment by mli** [comment]
Job PR-746/13 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-746/13/index.html

**Pull request merged**
