### PR TITLE
[DOC] Update sphinx mapping link to the new website

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
The object.inv is available now. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by szha** [comment]
http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-956/1/pipeline#step-198-log-1152

**Comment by leezu** [comment]
https://mxnet.apache.org/api/python/docs/api/objects.inv is not available

**Comment by eric-haibin-lin** [comment]
@ThomasDelteil wrong path?

**Comment by ThomasDelteil** [comment]
use that one. https://mxnet.apache.org/api/python/docs/objects.inv
apache does an interesting redirect here to https://mxnet.apache.org/api/python/docs/api/objects.inv if you open it in a browser

**Comment by leezu** [comment]
`[2019-10-08T20:50:08.722Z] /var/lib/jenkins/gluon-nlp-cpu-py3@2/docs/examples/sentence_embedding/elmo_sentence_representation.ipynb:154:undefined label: /api/modules/data.rst#gluonnlp.data.nltkmosestokenizer (if the link has no caption the label must precede a section header)
`

seems to fail due to https://github.com/dmlc/gluon-nlp/commit/93d25fa893d6ae657c777d30bfdc5ab4e0e70fed 

Need to rebase on master and force push.

(Also there is a fix in https://github.com/dmlc/gluon-nlp/pull/959 , so let's wait for it to be merged as CI will fail otherwise)

**Comment by mli** [comment]
Job PR-956/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-956/3/index.html

**Pull request closed without merging**
