### PR TITLE
enable edit on github link

### PR DESCRIPTION
**Pull request by szha**
## Description ##
enable "edit on github" button

### Essentials ###
- [ ] Changes are complete (i.e. I finished coding on this PR)

### Changes ###
- [x] enable edit on github button in rtd theme

### CODE REVIEW

**Comment by mli** [comment]
Job PR-337/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-337/1/index.html

**Comment by mli** [comment]
Job PR-337/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-337/5/index.html

**Comment by szha** [comment]
Still needs to tweak for the markdown-based notebooks.

**Comment by mli** [comment]
Job PR-337/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-337/6/index.html

**Comment by mli** [comment]
Job PR-337/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-337/8/index.html

**Comment by mli** [comment]
Job PR-337/9 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-337/9/index.html

**Comment by mli** [comment]
Job PR-337/12 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-337/12/index.html

**Pull request merged**
