### PR TITLE
[DOC] update mxnet version in installation doc

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
The doc is wrong. Updated to 1.6.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1072/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1072/2/index.html

**Comment by szha** [comment]
I think this only applies to the doc for master branch, which is updated automatically.

**Comment by leezu** [comment]
@szha yes, but it's currently broken even for the master branch. So the command should be fixed once the html page listing mxnet pre-releases for pip is ready.

**Comment by eric-haibin-lin** [comment]
That's reasonable. i bought up that we should publish the nightly build links to mxnet website on the dev list. But they are not yet available there. Then we can add a link on the gluonnlp master branch to all nightly builds.

**Pull request merged**
