### PR TITLE
npx.save -> npx.savez

### PR DESCRIPTION
**Pull request by leezu**
Update for https://github.com/apache/incubator-mxnet/commit/5dc404dfb0cb5e9a034c9db5d58721e15791ad33

### CODE REVIEW

**Comment by sxjscience** [comment]
We can merge after the nightly has been updated.

**Review by sxjscience — APPROVED** [review]
LGTM

**Comment by sxjscience** [comment]
@leezu Do you know what's the status of this PR?

**Comment by szha** [comment]
Rerunning the timed-out build to see if 20201127 wheel includes the miniz fix.

**Comment by sxjscience** [comment]
The speed is still slow I think. For the previous run, it took 1hour for completing the GPU test.

**Comment by szha** [comment]
I think the timeout issue due to serialization has been fixed (thanks @leezu). @sxjscience any idea about the name errors in the failed tests?

**Comment by sxjscience** [comment]
Does the 20201127 build include the miniz fix?

**Comment by sxjscience** [comment]
@szha The error message should be related to wikiextractors: Seems that the 3.0.0 version contains this bug. We will need to force the dependency to `wikiextractors==0.1`.

**Pull request merged**
