### PR TITLE
[DOC] Fix command line examples for text classification

### PR DESCRIPTION
**Pull request by kamatsuoka**
## Description ##
Command line examples for text classification have some copypasta errors

### Essentials ###
- [x ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x ] Changes are complete (i.e. I finished coding on this PR)
- [n/a] All changes have test coverage
- [n/a] Code is well-documented

### Changes ###
- [x] Changes to command-line args in example commands

## Comments ##
n/a

### CODE REVIEW

**Comment by mli** [comment]
Job PR-874/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-874/3/index.html

**Comment by mli** [comment]
Job PR-874/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-874/4/index.html

**Comment by mli** [comment]
Job PR-874/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-874/6/index.html

**Comment by eric-haibin-lin** [comment]
Thanks @kamatsuoka  for the fix!

**Pull request merged**
