### PR TITLE
Add BIG LSTM + CNN INPUTS to large_word_language_model.py

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Add character CNN embeddings training mode to large_word_language_model.py.

### Essentials ###
- [ ] Changes are complete (i.e. I finished coding on this PR)
  - [ ] Hyperparameter tuning
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Add BIG LSTM + CNN INPUTS to large_word_language_model.py
- [X] Allow selecting WikiText datasets for training `large_word_language_model.py` 

## Comments ##
- The PR includes ~~#235 #247 #250 as well as~~ (_already merged and rebased_) part of #246. Once these PRs are merged, the commits will be removed from this PR.
- Using WikiText-2 for training the model in the default configuration will result in heavy overfitting.

### CODE REVIEW

**Comment by leezu** [comment]
@eric-haibin-lin @cgraywang

**Comment by leezu** [comment]
Sure, thanks. Rebase is done.

It seems that the PrefetchingStream with 'process' worker type uncovers some issues in mxnet.random module in this script. mxnet will crash _sometimes_ when mx.random.seed() is called in the worker process: ```mxnet.base.MXNetError: [19:28:56]
src/common/random_generator.cu:58: Check failed: err == cudaSuccess (3 vs. 0)
Name: rand_generator_seed_kernel ErrStr:initialization error```

**Comment by eric-haibin-lin** [comment]
May be affected by https://github.com/dmlc/gluon-nlp/pull/278

**Comment by szha** [comment]
@leezu feel free to reopen when restarting on this.

**Pull request closed without merging**
