### PR TITLE
[API] Make BERT a hybrid block

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
This PR makes use of the infer_range attribute of the arange operator (thanks to @TaoLv and @leezu ) in MXNet to fully hybridize the BERT model. 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
The change is backward compatible. Added tests for model forward with and without optional inputs.

### CODE REVIEW

**Comment by mli** [comment]
Job PR-877/13 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/13/index.html

**Comment by eric-haibin-lin** [comment]
@leezu the contrib.arange_like operator is not available in mxnet 1.5, which gluonnlp depends on

**Comment by leezu** [comment]
Right, but there seems to be the workaround based on infer_range which you are using in this PR. That works on mxnet 1.5. Where does the workaround fall short?

**Comment by mli** [comment]
Job PR-877/14 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/14/index.html

**Comment by mli** [comment]
Job PR-877/15 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/15/index.html

**Comment by mli** [comment]
Job PR-877/16 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/16/index.html

**Comment by mli** [comment]
Job PR-877/17 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/17/index.html

**Comment by mli** [comment]
Job PR-877/18 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/18/index.html

**Comment by mli** [comment]
Job PR-877/19 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-877/19/index.html

**Comment by eric-haibin-lin** [comment]
@leezu good point. I removed the legacy bert model definition. please review again

**Pull request merged**
