### PR TITLE
[BUGFIX] Remove unused argument in fasttext_word_ngram.py

### PR DESCRIPTION
**Pull request by KurtJanssensCRW**
## Description ##
Small update to remove unused argument

In fasttext_word_ngram.py batch_size is used but batch-size is never used

### CODE REVIEW

**Comment by mli** [comment]
Job PR-486/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-486/1/index.html

**Comment by sravanbabuiitm** [comment]
group.add_argument('--batch_size', type=float, default=16)

This is being used in the code, please keep this and remove the :"batch-size"

**Comment by sravanbabuiitm** [comment]
we can change the type of "batch_size" to "int" from currently existing "float" type.

**Comment by mli** [comment]
Job PR-486/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-486/2/index.html

**Pull request merged**
