### PR TITLE
[DOC] remove wrong tutorial header level

### PR DESCRIPTION
**Pull request by szha**
## Description ##
remove wrong tutorial header level

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] fix wrong level

### CODE REVIEW

**Comment by szha** [comment]
image

TOC tree currently looks wrong.

**Comment by faramarzmunshi** [comment]
All of these tutorials will need to be rewritten or revised again by me as according to the style guidelines. I think we should stop implementing changes to the tutorials until the style guidelines have been cemented by @astonzhang  and me

**Comment by mli** [comment]
Job PR-826/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-826/1/index.html

**Comment by szha** [comment]
@faramarzmunshi the current inconsistent header level in the TOC is a release stopper.

**Comment by faramarzmunshi** [comment]
Ah okay my bad!

**Comment by mli** [comment]
Job PR-826/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-826/3/index.html

**Comment by mli** [comment]
Job PR-826/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-826/4/index.html

**Comment by mli** [comment]
Job PR-826/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-826/5/index.html

**Pull request merged**
