### PR TITLE
[CI] Enable CI for MXNet 1.6 pre-release

### PR DESCRIPTION
**Pull request by leezu**
Enable CI for MXNet 1.6 pre-release. We need to ensure that our code remains compatible with MXNet 1.6. Currently we're only testing against MXNet 1.7 pre-release version.

Based on a manual build uploaded to my S3 bucket. There are currently no public builds of MXNet 1.6 pre-release available.

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by leezu** [comment]
Blocked by https://github.com/apache/incubator-mxnet/issues/16933

**Comment by szha** [comment]
@leezu CI still needs fix

**Comment by mli** [comment]
Job PR-1023/16 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1023/16/index.html

**Comment by mli** [comment]
Job PR-1023/17 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1023/17/index.html

**Comment by mli** [comment]
Job PR-1023/19 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1023/19/index.html

**Pull request merged**
