### PR TITLE
Switch CI to Python 3.5 and declare Python 3.5 support

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Fixes https://github.com/dmlc/gluon-nlp/issues/994

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1009/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/4/index.html

**Comment by mli** [comment]
Job PR-1009/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/8/index.html

**Comment by mli** [comment]
Job PR-1009/10 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/10/index.html

**Comment by mli** [comment]
Job PR-1009/11 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/11/index.html

**Comment by mli** [comment]
Job PR-1009/12 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/12/index.html

**Comment by mli** [comment]
Job PR-1009/14 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/14/index.html

**Comment by leezu** [comment]
This currently removes `multiprocessing.Pool` usage with `BERTDatasetTransform` due to incompatibility with Python 3.5's pickle. Maybe we can refactor `BERTDatasetTransform` later.

**Comment by mli** [comment]
Job PR-1009/16 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1009/16/index.html

**Comment by sxjscience** [comment]
In terms of python3.5 v.s. python3.6, I think we can move to python3.6 in the next-gen (1.0) release. What do you think?

**Pull request merged**
