### PR TITLE
[Block] Use fused gelu operator

### PR DESCRIPTION
**Pull request by TaoLv**
## Description ##
Use fused gelu operator.

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1082/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1082/1/index.html

**Comment by TaoLv** [comment]
@eric-haibin-lin I assume that we need work on the master branch of gluonnlp. Please review.

**Comment by mli** [comment]
Job PR-1082/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1082/2/index.html

**Comment by mli** [comment]
Job PR-1082/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1082/3/index.html

**Pull request merged**
