### PR TITLE
[Parallel] Avoid race condition when downloading datasets

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
Acquire a file lock before downloading the dataset. This helps when using multi-processing for multi-GPU training, or multi-machine training with a shared file system 

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

### CODE REVIEW

**Comment by eric-haibin-lin** [comment]
https://github.com/dmlc/gluon-nlp/issues/726

**Comment by eric-haibin-lin** [comment]
Is there any recent change in numpy version on CI? The error does not seem to be relevant to the code changes.. @leezu

**Comment by leezu** [comment]
Yes. Numpy 1.18 is released and one of our dependencies is incompatible.

**Comment by leezu** [comment]
What kind of distributed filesystem are you using? It may be more efficient to cache the downloads on each machine locally. In my experience S3 is faster than for example EFS.
For multiprocessing, a workaround is to set the `MXNET_HOME` variable differently for each process?

I don't think MXNet upstream does locking / supports this? So introducing it only on the GluonNLP side may not be sufficient?

**Comment by leezu** [comment]
> os.rename(): atomic but does not support across file system. 

I'm not sure how this is related to our use-case. Files in the same directory will always be in the same filesystem. Here you are interested in downloading a file and making it atomically available once the download is complete. This operation does not involve cross-filesystem renames.

> We do have lots of users using EFS/FSX.

It's a bad practice to keep the MXNET_HOME on EFS. EFS is slower than just using S3 or EBS. Also it is much more expensive. As a cheap and better performant alternative I suggest you look into https://github.com/kahing/goofys/

But in either way, this should be unrelated to atomic rename and locking.

**Comment by eric-haibin-lin** [comment]
@leezu `os.lockf` is only available for Unix. I assume we don't want to stop supporting windows users. The advantage is that portalocker is portable across different operating systems. 

Yes, the support should be upstream'd to both gluon-nlp and mxnet

**Comment by leezu** [comment]
Yes, if file locking is supported on Windows and we want to use file-locking, we should also support Windows.

So how about we first use idempotent operations in GluonNLP until support is upstreamed? Then we can reuse the upstream implementation.

**Comment by sxjscience** [comment]
I think we can use the filelock. It's also used in sacrebleu: https://github.com/mjpost/sacreBLEU/blob/069b0c88fceb29f3e24c3c19ba25342a3e7f96cb/sacrebleu.py#L1154

**Comment by eric-haibin-lin** [comment]
> So how about we first use idempotent operations in GluonNLP until support is upstreamed? Then we can reuse the upstream implementation.

What do you recommend as the way to implement idempotent operations and avoid race condition?

**Comment by leezu** [comment]
File-renames within the same directory are idempotent and atomic. You mentioned above that rename is not supported across filesystems, but we don't need to cross-filesystem rename. The temporary file *with randomized name* should be in the same directory as the "target" file.

**Comment by mli** [comment]
Job PR-1078/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1078/3/index.html

**Comment by mli** [comment]
Job PR-1078/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1078/4/index.html

**Comment by mli** [comment]
Job PR-1078/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1078/5/index.html

**Pull request merged**
