### PR TITLE
[WEBSITE] adjust logo size

### PR DESCRIPTION
**Pull request by szha**
## Description ##
adjust logo size to reduce the margin

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)

### Changes ###
- [x] adjust logo size

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by szha** [comment]
let's rely on the website preview for making sure the logo is of the correct size

**Review by sxjscience — APPROVED** [review]

**Comment by sxjscience** [comment]
Actually, can we make it smaller?

**Comment by szha** [comment]
@sxjscience do you mean with more padding?

**Comment by sxjscience** [comment]
Yes, more padding.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by szha** [comment]
looks like we still need a bit more padding on the top?

**Comment by szha** [comment]
@sxjscience looks like some pyarrow-based datasets failed their tests. perhaps the data source has expired.

**Pull request merged**
