### PR TITLE
[Website]Lift timeout restriction on CI configuration

### PR DESCRIPTION
**Pull request by chenw23**
## Description ##
This pull request works together with the previous pull quest #1252 . #1252 works on the python script part and this pull request works on the Jenkins CI part.
They work together to solve the problem from #1230

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by chenw23** [comment]
Error log is below:
```
[2020-07-05T16:35:45.739Z] intersphinx inventory has moved: https://beta.mxnet.io/objects.inv -> https://mxnet.apache.org/
```
@szha It seems that an inventory on mxnet.io is not redirecting correctly? Which team is in charge of this part of work?
Thanks!

**Comment by szha** [comment]
I think the beta.mxnet.io is deprecated and we should find the alternative on mxnet.apache.org

**Comment by chenw23** [comment]
Fixed in #1256

**Comment by mli** [comment]
Job PR-1255/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1255/4/index.html

**Pull request merged**
