### PR TITLE
[CI] upgrade mxnet to 1.4.0

### PR DESCRIPTION
**Pull request by szha**
## Description ##
upgrade mxnet to 1.4.0

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage
- [x] Code is well-documented

### Changes ###
- [x] upgrade mxnet to 1.4.0
- [x] move doctest to be an independent step

### CODE REVIEW

**Comment by mli** [comment]
Job PR-617/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-617/4/index.html

**Comment by mli** [comment]
Job PR-617/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-617/5/index.html

**Comment by zhreshold** [comment]
I guess it's okay for ci, as long as 1.4.0 is available for linux already

**Comment by szha** [comment]
@zhreshold agreed. I submitted this as a way to verify that GluonNLP is working properly with mxnet 1.4.0 in preparation for the release.

**Comment by mli** [comment]
Job PR-617/6 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-617/6/index.html

**Pull request merged**
