### PR TITLE
Fix env/docker/py3.yml

### PR DESCRIPTION
**Pull request by leezu**
```
[2020-08-24T23:38:24.969Z] Traceback (most recent call last):

[2020-08-24T23:38:24.969Z]   File "docs/md2ipynb.py", line 5, in <module>

[2020-08-24T23:38:24.969Z]     import nbformat

[2020-08-24T23:38:24.969Z] ImportError: No module named 'nbformat'
```

### CODE REVIEW

**Comment by szha** [comment]
looks like notedown is missing in the docker for batch job.

**Comment by leezu** [comment]
The batch job doesn't make use of the conda environment anymore for some reason. Initially nbformat was missing, and it only becomes available via https://github.com/dmlc/gluon-nlp/pull/1325/commits/f2b23627afeaadf38f9137bd5c7aa175a1119513

Including nbformat into the conda yml file didn't help

**Comment by leezu** [comment]
Failed due to
```

2020-09-01 12:22:07
Pip subprocess error:
2020-09-01 12:22:07
ERROR: Could not find a version that satisfies the requirement numpy==1.19.1 (from -r /gluon-nlp/env/docker/condaenv._m5hzn7e.requirements.txt (line 1)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.11.0b3, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1)
2020-09-01 12:22:07
ERROR: No matching distribution found for numpy==1.19.1 (from -r /gluon-nlp/env/docker/condaenv._m5hzn7e.requirements.txt (line 1))
2020-09-01 12:22:07
CondaEnvException: Pip failed
```

**Comment by mli** [comment]
Job PR-1325/7 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1325/7/index.html

**Comment by mli** [comment]
Job PR-1325/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1325/8/index.html

**Comment by mli** [comment]
Job PR-1325/10 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1325/10/index.html

**Pull request merged**
