### PR TITLE
[v0.x] Backport CI from Master to v0.x

### PR DESCRIPTION
**Pull request by barry-jin**
## Description ##
fix issue #1529 

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by szha** [comment]
we probably need to move the test tasks to our own workers.

**Comment by szha** [comment]
`submit-job.py: error: unrecognized arguments: --conda-env docker/py3`

**Comment by barry-jin** [comment]
> `submit-job.py: error: unrecognized arguments: --conda-env docker/py3`

For v0.x CI, should we replace current jenkins CI with github actions or keep some of the jenkins jobs and move the others to github actions. In issue #1529, the jenkins CI will pass randomly, so I try to replace current jenkins CI with github actions by backporting the CI from master branch, including the submit-job.py script.

**Comment by szha** [comment]
OK. I removed the required status for the old jenkins checks.

**Review by leezu — APPROVED** [review]

**Pull request merged**
