### PR TITLE
Revert "Don't treat language model datasets special"

### PR DESCRIPTION
**Pull request by leezu**
Reverts dmlc/gluon-nlp#128

There is no consensus that usage of WikiText for non-LM purpose should be supported at the cost of making the LM API more complicated (by eg. making the `bptt_batchify` and `batchify` functions standalone).

### CODE REVIEW

**Comment by szha** [comment]
Thanks. I do think the general design of this refactor is a step in the right direction. This way, all the classes and interfaces are doing what they are supposed to, and WikiText classes will no longer be more specialized than what's necessary, which should open up possibility for more creative use and customization. Good design takes time, so thanks for proposing the change.

Let's review the design again after next release, and build consensus.

**Comment by mli** [comment]
Job PR-134/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-134/2/index.html

**Comment by mli** [comment]
Job PR-134/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-134/3/index.html

**Comment by szha** [comment]
The merit of the design is not from the results it can get, but rather the flexibility and right principles for API design

**Comment by cgraywang** [comment]
Yes, but I do think our package should balance between academic convention and flexible API usage

**Comment by szha** [comment]
They are not in conflict.

**Pull request merged**
