### PR TITLE
[MODEL] XLNet conversion scripts

### LINKED ISSUE #787: Port XLNet to gluonnlp
https://github.com/zihangdai/xlnet
https://arxiv.org/abs/1906.08237

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Add XLNet conversion scripts

### Essentials ###
- [X] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [X] Pretrained XLNet

### Comments ###
This PR resolves #787

### CODE REVIEW

**Comment by mli** [comment]
Job PR-866/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/1/index.html

**Comment by mli** [comment]
Job PR-866/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/2/index.html

**Comment by mli** [comment]
Job PR-866/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/4/index.html

**Comment by mli** [comment]
Job PR-866/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/5/index.html

**Comment by eric-haibin-lin** [comment]
Is this ready?

**Comment by leezu** [comment]
This only contains the model and no fine-tuning scripts. For finetuning, designing a joint API encompasses the existing bert scripts and works for XLNet and moving that to the main package would be a way forward. That can be done in a separate PR though I guess.

**Comment by szha** [comment]
@leezu pinging for an update

**Comment by szha** [comment]
@leezu @eric-haibin-lin gentle ping

**Comment by leezu** [comment]
@eric-haibin-lin an example is included now https://github.com/dmlc/gluon-nlp/pull/866/files#diff-820020a4c66a085eb27014cc377a8658

**Comment by mli** [comment]
Job PR-866/7 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/7/index.html

**Comment by mli** [comment]
Job PR-866/8 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/8/index.html

**Comment by mli** [comment]
Job PR-866/9 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/9/index.html

**Comment by mli** [comment]
Job PR-866/10 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/10/index.html

**Comment by mli** [comment]
Job PR-866/11 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/11/index.html

**Comment by mli** [comment]
Job PR-866/12 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/12/index.html

**Comment by mli** [comment]
Job PR-866/13 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/13/index.html

**Comment by mli** [comment]
Job PR-866/15 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-866/15/index.html

**Comment by leezu** [comment]
CI passes now

**Pull request merged**
