### PR TITLE
[FIX] Update embedding script 

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
## Description ##
Fix a few issues found in the embedding script:

- some documentation is outdated
- params_path is actually not passed to the object
- fix hardcoded indices in text processing
- display actual text used for getting the embedding (after truncation)
- (not a bug) add support for sentence-piece vocab
- (not a bug) drop py2 specific code

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by mli** [comment]
Job PR-1046/1 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1046/1/index.html

**Comment by mli** [comment]
Job PR-1046/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1046/2/index.html

**Comment by mli** [comment]
Job PR-1046/3 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1046/3/index.html

**Comment by mli** [comment]
Job PR-1046/4 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1046/4/index.html

**Comment by leezu** [comment]
`[2019-12-16T06:10:48.189Z] mxnet.base.MXNetError: [05:43:31] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "~/.mxnet/models/bert_12_768_12_book_corpus_wiki_en_uncased-75cc780f.params": No such file or directory
`

**Comment by mli** [comment]
Job PR-1046/5 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1046/5/index.html

**Pull request merged**
