### PR TITLE
Distribute subword vectors for pretrained fastText embeddings

### PR DESCRIPTION
**Pull request by leezu**
## Description ##
Currently GluonNLP only distributes the word level fastText models and users have to manually download the `.bin` fastText models with subword vectors to obtain vectors for OOV words. This PR adds a `load_ngrams` parameter to `token_embedding.FastText` which  if True results in downloading the subword vectors and attaching them as `unknown_lookup` to the resulting `TokenEmbedding` meaning that vectors for OOV are transparently computed.

### Essentials ###
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [X] All changes have test coverage
- [X] Code is well-documented

### Changes ###
- [X] Distribute subword vectors for pretrained fastText embeddings
- [X] Add Common Crawl fastText vectors https://fasttext.cc/docs/en/crawl-vectors.html
- [X] Fix loading serialized `TokenEmbedding` without unknown_vector
- [X] Fix `TokenEmbedding.allow_extend` not honored in `__getitem__` if `TokenEmbedding.unknown_autoextend` is True

### CODE REVIEW

**Comment by leezu** [comment]
@szha could you double check the ACL for the S3 bucket. It seems the files can still not be downloaded.

**Comment by mli** [comment]
Job PR-185/23 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-185/23/index.html

**Comment by mli** [comment]
Job PR-185/30 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-185/30/index.html

**Comment by mli** [comment]
Job PR-185/34 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-185/34/index.html

**Pull request merged**
