### PR TITLE
Add function to set seed 

### LINKED ISSUE #1110: [reproducibility] add util function to enhance reproducibility
There are a few seeds that may lead to nondeterministic training loss: 
```
random.seed(seed)
mx.random.seed(seed)
numpy.random.seed(seed)
```
Sometimes our users miss one of them. Shall we add an API `gluonnlp.utils.seed` to set the seed for all of them?

### PR DESCRIPTION
**Pull request by avinashsai**
Fixes #1110 

Added set_seed function in utils.seed.py for setting seed value to enhance reproducibility.

### CODE REVIEW

**Comment by leezu** [comment]
CI will be fixed by https://github.com/dmlc/gluon-nlp/pull/1152

**Comment by avinashsai** [comment]
@eric-haibin-lin any updates on this??

**Comment by mli** [comment]
Job PR-1151/2 is complete. 
Docs are uploaded to http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-1151/2/index.html

**Comment by avinashsai** [comment]
@eric-haibin-lin 
When I analyzed the failed build log it's due to sequence_sampler.py.

**Comment by avinashsai** [comment]
@eric-haibin-lin 
Please approve this PR.

**Pull request merged**
