### PR TITLE
[Fix] Try to fix data pipeline scheduled test (attempt 2)

### PR DESCRIPTION
**Pull request by sxjscience**
## Description ##
It seems that the test is still failing so I'm submitting this PR.

### Essentials ###
- [ ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage
- [ ] Code is well-documented

### Changes ###
- [ ] Feature1, tests, (and when applicable, API doc)
- [ ] Feature2, tests, (and when applicable, API doc)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

cc @dmlc/gluon-nlp-team

### CODE REVIEW

**Comment by szha** [comment]
What's the error? Is there a way to validate the fix short of committing?

**Comment by sxjscience** [comment]
https://github.com/dmlc/gluon-nlp/runs/1710545425?check_suite_focus=true

**Comment by szha** [comment]
The log doesn't seem to show where the encoding error happens so it's a bit unclear whether the patch is the right fix.

**Comment by sxjscience** [comment]
I'm also not sure. But currently do not have enough time to take a look.

**Review by leezu — APPROVED** [review]

**Pull request merged**
